apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: django-web
  namespace: django-brad
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - args:
            - '-c'
            - gunicorn btre.wsgi:application --bind 0.0.0.0:8000
          command:
            - /bin/bash
          env:
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  key: allowed-hosts
                  name: emlak-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db-name
                  name: emlak-secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: db-user
                  name: emlak-secret
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  key: db-pass
                  name: emlak-secret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: db-host
                  name: emlak-secret
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: emlak-secret
          image: harbor.example.com/mantislogic/django-brad:v2
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /admin
              port: 8000
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          name: web
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /admin
              port: 8000
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /admin
              port: 8000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /django_brad/media
              name: media
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
